---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-egg-configmap-preonline
  namespace: default
data:
  NODE_ENV: production
  APP_NAME: wave-egg
  CONFIG_MIDDLEWARE: acm
  ACM_ENDPOINT: acm.aliyun.com
  ACM_NAMESPACE: 1d2f6afc-3a26-4a71-a238-d8ea3202c2c1
  ACM_ACCESS_KEY: LTAItdM1DrDEbKFs
  ACM_SECRET_KEY: t5Pz5tGp0ffzre73TuuPssa8ayhX1i
  ACM_GROUP: food.eggcms
  ACM_DATA_ID: "serverpath"
  NET_WEB_HOST: 'http://test-www.wavewisdom-bj.com'
  MONGOOSE_URL: 'mongodb://eggcmsadmin:eggcmsadmin123@dds-m5e9bd9dc44a8d241517-pub.mongodb.rds.aliyuncs.com:3717/eggcms'
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wave-egg-deployment-preonline
  namespace: default
  labels:
    deployment: wave-egg-deployment-preonline
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: wave-egg-pod-preonline
  template:
    metadata:
      labels:
        pod: wave-egg-pod-preonline
    spec:
      nodeSelector:                    
        nodeGroup: preonline
      containers:
      - name: wave-egg
        image: registry.cn-beijing.aliyuncs.com/wavewisdom-bj-registry-develop/wave-egg:2.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline
              key: NODE_ENV
        - name: APP_NAME
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline
              key: APP_NAME
        - name: CONFIG_MIDDLEWARE
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline
              key: CONFIG_MIDDLEWARE
        - name: ACM_ENDPOINT
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key: ACM_ENDPOINT   
        - name: ACM_NAMESPACE
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key: ACM_NAMESPACE   
        - name: ACM_ACCESS_KEY
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key: ACM_ACCESS_KEY   
        - name: ACM_SECRET_KEY
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key: ACM_SECRET_KEY
        - name: ACM_GROUP
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline
              key: ACM_GROUP
        - name: ACM_DATA_ID
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-preonline
              key: ACM_DATA_ID
        - name: NET_WEB_HOST
          valueFrom:
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key:  NET_WEB_HOST
        - name: MONGOOSE_URL
          valueFrom:
            configMapKeyRef:
              name: wave-egg-configmap-preonline     
              key: MONGOOSE_URL
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: wave-egg-service-preonline
  namespace: default
  labels:
    service: wave-egg-service-preonline
spec:
  selector:
    pod: wave-egg-pod-preonline
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wave-egg-ingress-preonline
  namespace: default
spec:
  rules:                                                     
  - host: test-www.wavewisdom-bj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wave-egg-service-preonline
          servicePort: 80