---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-egg-configmap-online
  namespace: online-frontend
data:
  NODE_ENV: online
  APP_NAME: wave-egg
  CONFIG_MIDDLEWARE: acm
  ACM_ENDPOINT: acm.aliyun.com
  ACM_NAMESPACE: 4c473266-f3ea-4fd5-a355-d900a8d00247
  ACM_ACCESS_KEY: LTAItdM1DrDEbKFs
  ACM_SECRET_KEY: t5Pz5tGp0ffzre73TuuPssa8ayhX1i
  ACM_GROUP: food.eggcms
  ACM_DATA_ID: "serverpath"
  NET_WEB_HOST: 'http://www.wavewisdom-bj.com'
  MONGOOSE_URL: 'mongodb://eggcmsadmin:eggcmsadmin123@dds-m5e9bd9dc44a8d241517-pub.mongodb.rds.aliyuncs.com:3717/eggcms'
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wave-egg-deployment-online
  namespace: online-frontend
  labels:
    deployment: wave-egg-deployment-online
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: wave-egg-pod-online
  template:
    metadata:
      labels:
        pod: wave-egg-pod-online
    spec:
      nodeSelector:                    
        nodeGroup: online
      containers:
      - name: wave-egg
        image: registry.cn-beijing.aliyuncs.com/wavewisdom-bj-registry/wave-egg:2.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online
              key: NODE_ENV
        - name: APP_NAME
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online
              key: APP_NAME
        - name: CONFIG_MIDDLEWARE
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online
              key: CONFIG_MIDDLEWARE
        - name: ACM_ENDPOINT
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online     
              key: ACM_ENDPOINT   
        - name: ACM_NAMESPACE
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online     
              key: ACM_NAMESPACE   
        - name: ACM_ACCESS_KEY
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online     
              key: ACM_ACCESS_KEY   
        - name: ACM_SECRET_KEY
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online     
              key: ACM_SECRET_KEY
        - name: ACM_GROUP
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online
              key: ACM_GROUP
        - name: ACM_DATA_ID
          valueFrom:     
            configMapKeyRef:
              name: wave-egg-configmap-online
              key: ACM_DATA_ID
        - name: MONGOOSE_URL
          valueFrom:
            configMapKeyRef:
              name: wave-egg-configmap-online     
              key: MONGOOSE_URL
        - name: NET_WEB_HOST
          valueFrom:
            configMapKeyRef:
              name: wave-egg-configmap-online   
              key: NET_WEB_HOST
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wave-egg-ingress-online
  namespace: online-frontend
spec:
  rules:                                                     
  - host: www.wavewisdom-bj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wave-egg-service-online
          servicePort: 80
  - host: www.wavewisdom.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wave-egg-service-online
          servicePort: 80       
---
apiVersion: v1
kind: Service
metadata:
  name: wave-egg-service-online
  namespace: online-frontend
  labels:
    service: wave-egg-service-online
spec:
  selector:
    pod: wave-egg-pod-online
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
